# Generated by Django 3.2.9 on 2021-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hasBeenAssigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='hasVoted',
            field=models.BooleanField(default=False),
        ),
    ]
