# Generated by Django 3.2.9 on 2021-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211114_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
